# Copyright (c) 2026 B-Tree Labs
# SPDX-License-Identifier: Apache-2.0

"""Defense-in-depth gaps queued from the v1 redteam round (#133).

The v1 redteam pinned 129 tests + fixed 2 inline vulns; five
defense-in-depth gaps were filed in ``tests/redteam/README.md`` for
v1.1 hardening. This module pins the post-fix behavior (or queues
the larger fixes as ``xfail`` for v1.2).

Coverage:
  - Header version handling (refresh.py): malformed / out-of-range
    hash lengths must reject with a clear error.
  - whoami ANSI / control-char stripping (cli.py): a hostile API key
    with embedded ESC bytes must not render terminal-control chars
    when printed.
  - Symlink walk hardening (refresh / dendra refresh): queued for
    v1.2 once Python 3.13 becomes the min version.
  - Storage ABC pickle-forbidden docstring: queued for v1.2 (touches
    storage.py, owned by a peer change-stream).
  - Cloud SPKI pinning: queued for v1.2 (bigger work; needs config
    surface + cert-rotation story).
"""

from __future__ import annotations

import argparse

import pytest

pytestmark = pytest.mark.redteam


# ---------------------------------------------------------------------
# Gap 1: Header version / hash-length handling
# ---------------------------------------------------------------------


class TestHeaderHashLengthRange:
    """``parse_generated_header`` accepts a 32-hex-char blake2b-128 hash.
    A future Dendra version that ships a longer hash would otherwise
    quietly mismatch the regex and raise a generic ValueError; the
    fix names the version so operators know the file came from a
    newer Dendra.
    """

    def test_longer_hash_rejected_with_unsupported_version_message(self) -> None:
        """A 64-hex-char hash (e.g. blake2b-256) must reject with a
        message that names the unsupported header so the operator
        knows to upgrade Dendra rather than chasing a corrupt-file
        ghost.
        """
        from dendra import refresh as refresh_mod

        text = (
            "# Generated by Dendra v9.9.9.\n"
            "# Source: pkg.mod:fn\n"
            "# AST hash: " + ("a" * 64) + "\n"
            "# Content hash: " + ("b" * 64) + "\n"
            "body\n"
        )
        with pytest.raises(ValueError) as excinfo:
            refresh_mod.parse_generated_header(text)
        msg = str(excinfo.value)
        # The error must mention the version delta or "unsupported"
        # so the operator's first instinct is "upgrade Dendra", not
        # "the file is corrupt".
        assert "unsupported" in msg.lower() or "newer Dendra" in msg or "v9.9.9" in msg, (
            f"version-mismatch error should name the unsupported version; got: {msg!r}"
        )

    def test_zero_length_hash_rejected(self) -> None:
        """An empty hash field must reject (not silently pass-through)."""
        from dendra import refresh as refresh_mod

        text = (
            "# Generated by Dendra v1.0.0.\n"
            "# Source: pkg.mod:fn\n"
            "# AST hash: \n"  # empty after the colon
            "# Content hash: " + ("b" * 32) + "\n"
            "body\n"
        )
        with pytest.raises(ValueError):
            refresh_mod.parse_generated_header(text)

    def test_within_range_hash_still_accepted(self) -> None:
        """The current 32-hex-char blake2b-128 must continue to parse
        cleanly (regression guard against an over-tight range).
        """
        from dendra import refresh as refresh_mod

        text = (
            "# Generated by Dendra v1.0.0.\n"
            "# Source: pkg.mod:fn\n"
            "# AST hash: " + ("a" * 32) + "\n"
            "# Content hash: " + ("b" * 32) + "\n"
            "body\n"
        )
        h = refresh_mod.parse_generated_header(text)
        assert h.source_ast_hash == "a" * 32
        assert h.generated_content_hash == "b" * 32


# ---------------------------------------------------------------------
# Gap 2: whoami ANSI / control-char stripping
# ---------------------------------------------------------------------


class TestWhoamiAnsiStripping:
    """A hostile API key with embedded ANSI ESC sequences (or other
    control chars) must NOT render terminal-control bytes when
    ``dendra whoami`` prints the truncated key. The fix strips
    non-printable bytes before display; the underlying credential
    is unchanged.
    """

    def test_whoami_strips_ansi_escape_in_truncated_key(
        self, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
    ) -> None:
        """A key containing ESC[ (ANSI CSI) must not surface raw bytes
        in stdout. Specifically: no 0x1b byte in the printed line.
        """
        from dendra.cli import cmd_whoami

        # Embed ESC + CSI sequence "set background red". Real terminals
        # would render it as a color flip; we want it stripped.
        hostile_key = "AAAAAAAA\x1b[41mBBBBBBBB"
        monkeypatch.setenv("DENDRA_API_KEY", hostile_key)
        rc = cmd_whoami(argparse.Namespace())
        out = capsys.readouterr().out
        assert rc == 0
        assert "\x1b" not in out, f"whoami leaked an ESC byte in the rendered output: {out!r}"

    def test_whoami_strips_other_control_chars(
        self, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
    ) -> None:
        """BEL (\\x07), backspace (\\x08), VT (\\x0b), DEL (\\x7f) are
        all non-printable and should be stripped when surfacing the
        truncated key.
        """
        from dendra.cli import cmd_whoami

        hostile_key = "PREFIX_\x07\x08\x0b\x0c\x7f_SUFFIX_1234"
        monkeypatch.setenv("DENDRA_API_KEY", hostile_key)
        rc = cmd_whoami(argparse.Namespace())
        out = capsys.readouterr().out
        assert rc == 0
        for forbidden in ("\x07", "\x08", "\x0b", "\x0c", "\x7f"):
            assert forbidden not in out, (
                f"whoami leaked control byte {forbidden!r} in output: {out!r}"
            )

    def test_whoami_preserves_normal_printable_chars(
        self, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
    ) -> None:
        """Sanitization must not destroy normal printable chars. Pin
        that an ordinary key still surfaces its first 8 + last 4 in
        the truncated form.
        """
        from dendra.cli import cmd_whoami

        monkeypatch.setenv("DENDRA_API_KEY", "abcdefghijklmnop1234")
        rc = cmd_whoami(argparse.Namespace())
        out = capsys.readouterr().out
        assert rc == 0
        assert "abcdefgh" in out
        assert "1234" in out
        assert "..." in out


# ---------------------------------------------------------------------
# Gap 3 (queued v1.2): follow_symlinks=False on refresh walk
# ---------------------------------------------------------------------


@pytest.mark.xfail(
    reason=(
        "Queued for v1.2: ``follow_symlinks=False`` on Path.glob / "
        "Path.iterdir requires Python 3.13. Dendra's ``requires-python`` "
        "is currently >=3.10; the resolved-under-root check in cmd_refresh "
        "already catches the symlink-escape attack at a coarser layer "
        "(see test_refresh_walk_does_not_follow_symlink_to_outside)."
    ),
    strict=True,
)
def test_refresh_walk_uses_follow_symlinks_false() -> None:
    """Pin the post-fix contract: every Path.rglob / Path.iterdir call
    in cmd_refresh passes ``follow_symlinks=False``. The current
    code does not (Python 3.10 doesn't support that kwarg), so this
    test xfails until the min Python bump.
    """
    import inspect

    from dendra import cli

    src = inspect.getsource(cli.cmd_refresh)
    # Both walk calls must pass follow_symlinks=False once we land on 3.13.
    assert src.count("follow_symlinks=False") >= 1


# ---------------------------------------------------------------------
# Gap 4 (queued v1.2): Storage ABC pickle-forbidden docstring
# ---------------------------------------------------------------------


@pytest.mark.xfail(
    reason=(
        "Queued for v1.2: storage.py is owned by a peer change-stream "
        "in this branch (concurrency rewrite); coordinating the "
        "docstring edit to avoid conflicts. Underlying guarantee is "
        "already in the README threat-model table; pickle vector is "
        "documented as caller-responsibility."
    ),
    strict=True,
)
def test_storage_abc_docstring_forbids_pickle() -> None:
    """``StorageBase`` (and the ``Storage`` Protocol) must carry a
    docstring stating ``MUST NOT use pickle`` so subclassers cannot
    plausibly land a pickle-deserialization sink and claim
    ignorance.
    """
    from dendra.storage import Storage, StorageBase

    abc_doc = (StorageBase.__doc__ or "").lower()
    proto_doc = (Storage.__doc__ or "").lower()
    assert "must not use pickle" in abc_doc or "must not use pickle" in proto_doc, (
        "Storage ABC must document the no-pickle invariant inline."
    )


# ---------------------------------------------------------------------
# Gap 5 (queued v1.2): Cloud SPKI cert pinning
# ---------------------------------------------------------------------


@pytest.mark.xfail(
    reason=(
        "Queued for v1.2: cert-pinning needs a config surface "
        "(env var or credentials field), a cert-rotation story, and "
        "an opt-out for users behind a corporate MITM proxy. The v1 "
        "round relies on system CA trust + verify=True (already pinned "
        "by tests in test_tls_and_cloud.py)."
    ),
    strict=True,
)
def test_cloud_sync_supports_optional_spki_pinning() -> None:
    """Pin the post-fix contract: ``dendra.cloud.sync`` exposes a
    hook (constant or env var) that, when set to a hex SPKI hash,
    causes outbound calls to verify the server's cert against that
    pinned key. Until v1.2 lands, the symbol simply doesn't exist.
    """
    from dendra.cloud import sync

    # The pin-checking helper or env-var name will be added in v1.2.
    # Naming the surface up-front locks the contract.
    assert hasattr(sync, "DENDRA_CLOUD_SPKI_PIN") or hasattr(sync, "verify_spki_pin")
