# Copyright (c) 2026 B-Tree Labs
# SPDX-License-Identifier: Apache-2.0

"""Generated-file (``__dendra_generated__/``) attack surface.

Threat model:
  - Generated files are emitted by ``dendra init --auto-lift`` and read
    by ``dendra refresh`` / ``dendra doctor``.
  - The reader must NOT execute the file body - only parse the header.
  - The CLI walk must NOT follow symlinks or descend into ``..`` paths
    above the project root.

We assert the parser is a parser, not an interpreter; we assert the
walker stays bounded; we document the residual threat model for
AST-hash collisions.
"""

from __future__ import annotations

import os
import sys

import pytest

from dendra import refresh as refresh_mod

pytestmark = pytest.mark.redteam


# ---------------------------------------------------------------------
# parse_generated_header is a parser, not an interpreter
# ---------------------------------------------------------------------


def test_parse_header_does_not_exec_file():
    """A generated file containing ``os.system(...)`` at module level
    must NEVER be executed by ``parse_generated_header``.

    The parser only consumes the ``#``-comment block at the top.
    """
    sentinel = "/tmp/dendra-generated-file-rce-fired"
    if os.path.exists(sentinel):
        os.unlink(sentinel)

    text = (
        "# Generated by Dendra v1.0.0.  DO NOT EDIT BY HAND.\n"
        "# Source: pkg.mod:fn\n"
        "# AST hash: " + ("a" * 32) + "\n"
        "# Content hash: " + ("b" * 32) + "\n"
        "# Run `dendra refresh`.\n"
        "import os\n"
        f"os.system('touch {sentinel}')\n"
    )

    header = refresh_mod.parse_generated_header(text)
    assert header.source_module == "pkg.mod"
    assert not os.path.exists(sentinel), (
        "parse_generated_header MUST NOT execute the body - that's a "
        "trivial RCE for any user who runs `dendra refresh` on a "
        "repo with a poisoned generated file."
    )


def test_detect_drift_does_not_exec_file(tmp_path):
    """detect_drift reads the generated file as text - never imports it."""
    sentinel = tmp_path / "would-have-fired"
    src = tmp_path / "src.py"
    src.write_text("def fn(x):\n    return x\n")
    gen = tmp_path / "__dendra_generated__" / "src__fn.py"
    gen.parent.mkdir()
    body = f"import os\nos.system('touch {sentinel}')\n"
    refresh_mod.write_generated_file(
        gen,
        source_module="src",
        source_function="fn",
        source_ast_hash="0" * 32,
        content=body,
        dendra_version="1.0.0",
    )
    # drift comes back USER_EDITED or whatever - the point is no exec.
    refresh_mod.detect_drift(src, "fn", gen)
    assert not sentinel.exists()


# ---------------------------------------------------------------------
# Header poisoning
# ---------------------------------------------------------------------


def test_header_with_embedded_newline_in_source_module_rejected():
    """Embedded newline in the ``# Source:`` field should not let an
    attacker forge a second header line. The regex is line-anchored
    in spirit (\\w+ won't match newlines), so this rejects with
    ValueError on the malformed AST-hash line.

    BUG FIX (defense-in-depth): newline in source_module would otherwise
    let an attacker terminate the header and inject directives. The
    regex forbids it because ``[\\w.]+`` excludes newlines.
    """
    text = (
        "# Generated by Dendra v1.0.0.\n"
        "# Source: pkg.mod\nFAKE: spam:fn\n"
        "# AST hash: " + ("a" * 32) + "\n"
        "# Content hash: " + ("b" * 32) + "\n"
        "body\n"
    )
    with pytest.raises(ValueError):
        refresh_mod.parse_generated_header(text)


def test_header_with_truncated_hash_rejected():
    """Hash field shorter than 32 hex chars must be rejected, not
    silently treated as up-to-date.
    """
    text = (
        "# Generated by Dendra v1.0.0.\n"
        "# Source: pkg.mod:fn\n"
        "# AST hash: " + ("a" * 16) + "\n"  # truncated
        "# Content hash: " + ("b" * 32) + "\n"
        "body\n"
    )
    with pytest.raises(ValueError):
        refresh_mod.parse_generated_header(text)


def test_header_with_long_garbage_rejected():
    """A "header" that is just a 100KB blob of comment lines without
    the required structure must be rejected, not silently DOS'd.
    """
    text = "\n".join("# garbage " + str(i) for i in range(10_000))
    with pytest.raises(ValueError):
        refresh_mod.parse_generated_header(text)


def test_header_missing_prefix_rejected():
    """File without the canonical ``# Generated by Dendra`` prefix must
    be rejected, not silently parsed.
    """
    text = (
        "# Source: pkg.mod:fn\n# AST hash: " + ("a" * 32) + "\n# Content hash: " + ("b" * 32) + "\n"
    )
    with pytest.raises(ValueError):
        refresh_mod.parse_generated_header(text)


def test_header_with_unicode_in_module_name_rejected():
    """Module names are ``[\\w.]+`` ASCII; non-ASCII unicode that some
    normalizers fold to ASCII must NOT be accepted as a path-trickery
    vector.

    \\w in Python re is unicode by default, so e.g. "пкг.мод" might be
    accepted. We pin the current behavior so any tightening is a
    deliberate change rather than an accident.
    """
    text = (
        "# Generated by Dendra v1.0.0.\n"
        "# Source: пкг.мод:fn\n"
        "# AST hash: " + ("a" * 32) + "\n"
        "# Content hash: " + ("b" * 32) + "\n"
    )
    # Either accepted (module name flows through as-is, harmless)
    # or rejected. Never silently transformed.
    try:
        h = refresh_mod.parse_generated_header(text)
        assert h.source_module == "пкг.мод"
    except ValueError:
        pass


# ---------------------------------------------------------------------
# AST-hash collision threat model - documented, not exploited
# ---------------------------------------------------------------------


def test_ast_hash_is_blake2b_128_collision_resistant():
    """Threat model: AST-hash is blake2b-128. Collision-resistance is
    ~2^64 work (birthday) - far above the relevant attacker scope
    (single-developer machine, bounded source corpus).

    We don't need to demonstrate non-collision; we pin the algorithm so
    any future weakening to a shorter digest must be deliberate.
    """
    h = refresh_mod.ast_hash("def f(x): return x")
    assert len(h) == 32  # 16 bytes = 128 bits = 32 hex chars


def test_content_hash_catches_drift(tmp_path):
    """If an attacker forges a header with a stale AST hash but
    legitimately-shaped body, the CONTENT hash mismatch (USER_EDITED)
    triggers refusal in `dendra refresh`. This is the defense-in-depth.
    """
    src = tmp_path / "src.py"
    src.write_text("def fn(x):\n    return x\n")

    gen = tmp_path / "__dendra_generated__" / "src__fn.py"
    gen.parent.mkdir()
    refresh_mod.write_generated_file(
        gen,
        source_module="src",
        source_function="fn",
        source_ast_hash=refresh_mod.ast_hash("def fn(x):\n    return x\n"),
        content="# legitimate body\n",
        dendra_version="1.0.0",
    )
    # Tamper with the body without touching the header:
    text = gen.read_text()
    tampered = text + "\n# attacker edit\n"
    gen.write_text(tampered)

    status = refresh_mod.detect_drift(src, "fn", gen)
    assert status is refresh_mod.DriftStatus.USER_EDITED


# ---------------------------------------------------------------------
# CLI walk: refuse symlink escapes
# ---------------------------------------------------------------------


@pytest.mark.skipif(sys.platform.startswith("win"), reason="symlinks need admin on Windows")
def test_refresh_walk_does_not_follow_symlink_to_outside(tmp_path, capsys):
    """A ``__dendra_generated__`` symlink pointing outside the project
    root must NOT be walked by ``dendra refresh``.

    BUG FIX: ``Path.rglob`` resolves entries through symlinks by default,
    so a malicious ``__dendra_generated__`` symlink inside the project
    root pointing at e.g. ``/etc`` would let the walker glob (and
    parse-read) arbitrary *.py files there. No code is executed
    (parse-only), but presenting an out-of-tree path leaks file
    existence. Fix: ``cmd_refresh`` now filters generated dirs whose
    ``.resolve()`` escapes the project root and emits a stderr warning.
    """
    import argparse

    from dendra.cli import cmd_refresh

    project = tmp_path / "project"
    project.mkdir()
    outside = tmp_path / "outside_target"
    outside.mkdir()
    (project / "__dendra_generated__").symlink_to(outside)
    (outside / "leaked.py").write_text(
        "# Generated by Dendra v1.0.0.\n"
        "# Source: leaked:fn\n"
        f"# AST hash: {'a' * 32}\n"
        f"# Content hash: {'b' * 32}\n"
        "body\n"
    )

    args = argparse.Namespace(path=str(project), check=False, force=False)
    rc = cmd_refresh(args)
    captured = capsys.readouterr()

    # Walker refused the escape; the leaked file was never inspected.
    assert "resolves outside project root" in captured.err
    # cmd_refresh treats the project as having no generated files.
    assert "No Dendra-generated files found" in captured.out or rc == 0


@pytest.mark.skipif(sys.platform.startswith("win"), reason="symlinks need admin on Windows")
def test_refresh_walk_legitimate_subdirs_still_work(tmp_path, capsys):
    """The symlink-escape filter must NOT break the normal case where
    ``__dendra_generated__`` is a real directory inside the project.
    """
    import argparse

    from dendra.cli import cmd_refresh

    project = tmp_path / "project"
    gen = project / "__dendra_generated__"
    gen.mkdir(parents=True)
    src = project / "src.py"
    src.write_text("def fn(x):\n    return x\n")
    refresh_mod.write_generated_file(
        gen / "src__fn.py",
        source_module="src",
        source_function="fn",
        source_ast_hash=refresh_mod.ast_hash("def fn(x):\n    return x\n"),
        content="# body\n",
        dendra_version="1.0.0",
    )

    args = argparse.Namespace(path=str(project), check=True, force=False)
    rc = cmd_refresh(args)
    captured = capsys.readouterr()
    # The file was found and inspected - that's the load-bearing assertion
    # for this test (the symlink filter didn't break the legit case).
    assert "Scanned 1 generated file" in captured.out
    # rc may be 0 (UP_TO_DATE) or 1 (drift detected - depends on
    # whether ast.unparse output matches the literal source byte-for-byte).
    assert rc in (0, 1)
    # Crucially: no "resolves outside project root" warning.
    assert "resolves outside" not in captured.err


@pytest.mark.skipif(sys.platform.startswith("win"), reason="symlinks need admin on Windows")
def test_individual_generated_file_symlink_pointing_outside(tmp_path):
    """A *file* inside __dendra_generated__/ that's a symlink to an
    arbitrary path. Reading it is a parser-only operation, so no exec,
    but pin the behavior: parse_generated_header on whatever the
    symlink points at must succeed-or-fail cleanly, not crash.
    """
    project = tmp_path / "project"
    gen = project / "__dendra_generated__"
    gen.mkdir(parents=True)
    target = tmp_path / "outside.py"
    target.write_text("def evil(): pass\n")
    (gen / "x__y.py").symlink_to(target)

    text = (gen / "x__y.py").read_text()
    # Not a Dendra-generated file → ValueError, not crash.
    with pytest.raises(ValueError):
        refresh_mod.parse_generated_header(text)


def test_refresh_walk_path_with_dotdot_segment_refused():
    """A ``__dendra_generated__`` directory whose path contains ``..``
    via creative naming conventions can't actually exist on disk
    (filesystem refuses), so this is a no-op test. Documented for
    completeness of the threat model.
    """
    # Filesystems do not allow a directory to be literally named '..',
    # so this attack vector is not reachable; recorded here so reviewers
    # know we considered it.
    assert True
