# Copyright (c) 2026 B-Tree Labs
# SPDX-License-Identifier: Apache-2.0

"""Generated-file lifecycle: hash, drift detect, regenerate, refuse.

Postrule's auto-lifters (``src/postrule/lifters/*``) emit Python modules
into ``__postrule_generated__/`` directories alongside the user's source.
Those files have a structured header with two hashes:

- ``Source AST hash``: hash of the original function's AST at the moment
  the file was generated. Re-hash the current source; mismatch means
  the source drifted and the generated file is stale.
- ``Generated content hash``: hash of the file body below the header,
  computed at generation time. Re-hash the body; mismatch means a
  human edited the generated file, and ``postrule refresh`` will refuse
  to overwrite without ``--force``.

This module is the foundation for ``postrule refresh`` (regenerate on
drift) and ``postrule doctor`` (find missing/orphaned files). The CLI
wiring lives in ``src/postrule/cli.py``.
"""

from __future__ import annotations

import ast
import enum
import hashlib
import re
import textwrap
from dataclasses import dataclass
from pathlib import Path

_HEADER_PREFIX = "# Generated by Postrule"
_RE_VERSION = re.compile(r"# Generated by Postrule v(?P<version>\d+(?:\.\d+)*)")
_RE_SOURCE = re.compile(r"# Source:\s*(?P<module>[\w.]+):(?P<func>\w+)")
_RE_AST_HASH = re.compile(r"# AST hash:\s*(?P<hash>[0-9a-f]+)")
_RE_CONTENT_HASH = re.compile(r"# Content hash:\s*(?P<hash>[0-9a-f]+)")
_HASH_LEN = 32  # blake2b digest size in hex chars when digest_size=16
# Min/max range pinned for v1: any future widening of the digest needs
# a coordinated header-version bump so old clients refuse the new file
# with an "unsupported Postrule version" message instead of silently
# mis-parsing the hash.
_HASH_MIN_LEN = 32
_HASH_MAX_LEN = 32


# ----------------------------------------------------------------------
# AST hash. Stable under formatting; sensitive to logic.
# ----------------------------------------------------------------------


def ast_hash(source: str) -> str:
    """Hash the AST of a Python source snippet.

    Uses ``ast.dump`` with ``annotate_fields=True`` and excludes line/col
    info via ``include_attributes=False``. Whitespace and comments are
    stripped by ``ast.parse`` itself; docstrings remain (they're real
    AST nodes). Variable names are NOT normalized: a rename that
    affects the lifter's output should trigger regeneration.
    """
    tree = ast.parse(source)
    canonical = ast.dump(tree, annotate_fields=True, include_attributes=False)
    digest = hashlib.blake2b(canonical.encode("utf-8"), digest_size=16)
    return digest.hexdigest()


def _content_hash(body: str) -> str:
    """Hash the body of a generated file (everything below the header)."""
    digest = hashlib.blake2b(body.encode("utf-8"), digest_size=16)
    return digest.hexdigest()


# ----------------------------------------------------------------------
# Generated header — the structured top-of-file block we read and write.
# ----------------------------------------------------------------------


@dataclass(frozen=True)
class GeneratedHeader:
    """Parsed representation of the generated-file header."""

    postrule_version: str
    source_module: str
    source_function: str
    source_ast_hash: str
    generated_content_hash: str


def _format_header(
    *,
    postrule_version: str,
    source_module: str,
    source_function: str,
    source_ast_hash: str,
    generated_content_hash: str,
) -> str:
    """Render the canonical header block."""
    return textwrap.dedent(
        f"""\
        # Generated by Postrule v{postrule_version}.  DO NOT EDIT BY HAND.
        # Source: {source_module}:{source_function}
        # AST hash: {source_ast_hash}
        # Content hash: {generated_content_hash}
        # Run `postrule refresh` to regenerate after the source changes.
        # Manual edits will be overwritten unless you pass --force.
        """
    )


def write_generated_file(
    out_path: Path,
    *,
    source_module: str,
    source_function: str,
    source_ast_hash: str,
    content: str,
    postrule_version: str,
) -> None:
    """Write a generated file with the standard header at ``out_path``.

    Creates parent directories as needed. The content hash is computed
    over ``content`` (the body, excluding the header).
    """
    out_path.parent.mkdir(parents=True, exist_ok=True)
    body = content if content.endswith("\n") else content + "\n"
    header = _format_header(
        postrule_version=postrule_version,
        source_module=source_module,
        source_function=source_function,
        source_ast_hash=source_ast_hash,
        generated_content_hash=_content_hash(body),
    )
    out_path.write_text(header + body)


def parse_generated_header(text: str) -> GeneratedHeader:
    """Parse the structured header at the top of a generated file.

    Raises ``ValueError`` if the file isn't recognizably Postrule-generated
    or any required header line is malformed.
    """
    if _HEADER_PREFIX not in text.split("\n")[0]:
        raise ValueError(
            "File does not start with a Postrule generated-file header "
            f"({_HEADER_PREFIX!r}). Refusing to interpret as managed."
        )
    m_ver = _RE_VERSION.search(text)
    m_src = _RE_SOURCE.search(text)
    m_ast = _RE_AST_HASH.search(text)
    m_content = _RE_CONTENT_HASH.search(text)
    if not (m_ver and m_src and m_ast and m_content):
        raise ValueError(
            "Generated file header is malformed (missing version/source/"
            "hash line). Probably hand-edited or written by an older "
            "Postrule version. Run `postrule doctor` for diagnostics."
        )
    ast_h = m_ast.group("hash")
    content_h = m_content.group("hash")
    # Two hash-length failure modes, each with a distinct error so the
    # operator can tell "this file is corrupt" from "this file came
    # from a newer Postrule than I have installed".
    if len(ast_h) > _HASH_MAX_LEN or len(content_h) > _HASH_MAX_LEN:
        version = m_ver.group("version")
        raise ValueError(
            f"Generated file uses an unsupported header hash length "
            f"(AST={len(ast_h)}, content={len(content_h)}, "
            f"max={_HASH_MAX_LEN}); this file was likely written by a "
            f"newer Postrule (v{version}); upgrade your Postrule install or "
            f"regenerate after downgrading the source."
        )
    if len(ast_h) < _HASH_MIN_LEN or len(content_h) < _HASH_MIN_LEN:
        raise ValueError(
            f"Generated file has malformed hash (expected at least "
            f"{_HASH_MIN_LEN} hex chars, got AST={len(ast_h)} "
            f"content={len(content_h)})."
        )
    if len(ast_h) != _HASH_LEN or len(content_h) != _HASH_LEN:
        raise ValueError(
            f"Generated file has malformed hash (expected {_HASH_LEN} "
            f"hex chars, got AST={len(ast_h)} content={len(content_h)})."
        )
    return GeneratedHeader(
        postrule_version=m_ver.group("version"),
        source_module=m_src.group("module"),
        source_function=m_src.group("func"),
        source_ast_hash=ast_h,
        generated_content_hash=content_h,
    )


# ----------------------------------------------------------------------
# Drift detection — reconcile a (source, generated) pair.
# ----------------------------------------------------------------------


class DriftStatus(enum.Enum):
    """Outcome of comparing one source function against its generated file."""

    UP_TO_DATE = "up_to_date"  # both hashes match
    SOURCE_DRIFT = "source_drift"  # source changed; regenerate
    USER_EDITED = "user_edited"  # generated file was hand-edited
    MISSING_GENERATED = "missing"  # source exists, no generated file
    ORPHANED = "orphaned"  # generated file exists, source function gone


def _extract_function_source(source_text: str, function_name: str) -> str | None:
    """Return the source of ``function_name`` from ``source_text``, or
    ``None`` if no top-level function with that name exists.
    """
    tree = ast.parse(source_text)
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == function_name:
            return ast.unparse(node)
    return None


def _split_header_and_body(text: str) -> tuple[str, str]:
    """Split a generated file into (header_block, body).

    The header is the contiguous run of ``#``-comment lines at the top of
    the file. The body is everything after, exactly as written (so the
    content hash round-trips byte-for-byte).
    """
    lines = text.split("\n")
    header_end = 0  # exclusive index of first body line
    for i, line in enumerate(lines):
        if line.startswith("#"):
            header_end = i + 1
        else:
            break
    header = "\n".join(lines[:header_end])
    body = "\n".join(lines[header_end:])
    return header, body


def detect_drift(
    source_path: Path,
    function_name: str,
    generated_path: Path,
) -> DriftStatus:
    """Compare a source function against its generated file. Returns one
    of the :class:`DriftStatus` outcomes.

    The function is identified by ``function_name`` because a single
    source file can host many ``@ml_switch``-decorated functions, each
    with its own generated module.
    """
    if not generated_path.exists():
        return DriftStatus.MISSING_GENERATED

    source_text = source_path.read_text()
    fn_src = _extract_function_source(source_text, function_name)
    if fn_src is None:
        return DriftStatus.ORPHANED

    gen_text = generated_path.read_text()
    header = parse_generated_header(gen_text)
    _, body = _split_header_and_body(gen_text)

    current_source_hash = ast_hash(fn_src)
    current_content_hash = _content_hash(body)

    if current_content_hash != header.generated_content_hash:
        return DriftStatus.USER_EDITED
    if current_source_hash != header.source_ast_hash:
        return DriftStatus.SOURCE_DRIFT
    return DriftStatus.UP_TO_DATE
